# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

VM_BOX = ENV["VM_BOX"] || "peru/windows-server-2022-standard-x64-eval"
VM_RAM = ENV["VM_RAM"] || "1024"
VM_CPU = ENV["VM_CPU"] || "2"
N = ENV["N"] || 1

VM_NAME = ENV["VM_NAME"] || "windows-server-2022"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = VM_BOX
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "libvirt" do |lv|
    lv.memory = VM_RAM
    lv.cpus = VM_CPU
  end
  config.vm.provider "virtualbox" do |vb|
    vb.memory = VM_RAM
    vb.cpus = VM_CPU
  end

  (1..N.to_i).each do |a|
    config.vm.define "#{VM_NAME}-#{a}" do |vm|
      vm.vm.hostname = "#{VM_NAME}-#{a}"
    end
  end

end
